### ISSUE TITLE
Use a template engine OR React

### ISSUE THREAD

**Issue by federico-fiorini** [markos84uk/potential-train-wreck#3]
First of all great job here! I think next step (after cleaning up the repo as Chase suggested in #1 ) would be to move away from rendering HTML from the express endpoint. You can use two approaches:
- use a [template engine](https://expressjs.com/en/resources/template-engines.html) to dynamically set values in your HTML. E.g. in our dashboard we use Jade (now [Pug](https://github.com/pugjs/pug)). You can define your templates as separate files and from your express routes `render` the templates and pass some variables to them (that you'll use in the templates to set dynamic data). Templates can also be composed: you can have a `layout` template that's extendable by other templates that only care about a specific part of the page (e.g. your todo list could be a template that extends a page-layout template).
- use React. Your nodejs server can serve a react app. The react app will communicate to the server through API endpoints (e.g. to add a new item or list the existing items) and render content dynamically client side

**Comment by markos84uk** [comment]
https://github.com/markos84uk/potential-train-wreck/issues/1#issuecomment-570692294
